---
title: 'A new old project'
author: Renzo C. Silva
date: '2019-09-16'
slug: a-new-old-project
categories: []
tags: []
description: ''
thumbnail: images/tn.png
---

**In 2018**, I engaged in a project, hired by a small environmental consultancy firm, to develop a web application (R Shiny). The idea was to simply automate part of their typical data processing workflow, for time-saving purposes, and develop a few data visualization elements to assist in their reporting. As I was familiar with the subject area, I could confidently go one step further and help to improve the workflow per se, including designing and implementing new metrics and processes. 

**An R-Shiny app was then deployed in a cloud server.** Happy client, great science, very exciting project... then life moves on.   

## <span style="color:darkred">Fast-forward 12 months</span>

<p align = 'center'><iframe src="https://giphy.com/embed/t9lo3ViuLZaKTdM7xq" width="480" height="284" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></p>

**Here I am working on it again!** :smile:   

The project extension is focused (a) on the data preparation before its consumption by the previous app, and (b) making the algorithm fully customizable so that the experts, with some basic R skills, could tweak **any** parameters within it. 

**Reproducible science at its core!** Building such an R Markdown document has been extremely **joyful**! 


## <span style="color:darkred">So what?</span> 

The [USGS Database post series](https://renzocsilva.ca/posts/usgs-geochemdb-part1/) can wait. :wink:  


## <span style="color:darkred">Call for action</span>


If you are unfamiliar with R Markdown, see [this](https://rmarkdown.rstudio.com/authoring_quick_tour.html#overview) and [this](https://rmarkdown.rstudio.com/lesson-1.html) - and of course, [this book](https://bookdown.org/yihui/rmarkdown/) and the [R Markdown cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf). It will quickly become obvious it is a powerful tool to create documents for presentations, code documentation, teaching, and beyond. Check the [R Markdown gallery](https://rmarkdown.rstudio.com/gallery.html) for examples of utilization. There are a few extra resources you can use to 'beautify' your rendered documents, such as [this](https://cran.r-project.org/web/packages/prettydoc/vignettes/hpstr.html) and [this](https://slides.yihui.name/xaringan/). 


Particularly useful to those starting to try R Markdown out, [Holtz Yan](https://github.com/holtzy/) prepared a very nice [compilation](https://holtzy.github.io/Pimp-my-rmd/) of quick tricks to customize R Markdown documents.  

**Cheers!**








