---
categories: []
date: "2019-08-21"
slug: a-personal-website-is-born
tags: []
title: A personal website is born!
output: html
---

## It was about time...

I've been thinking about having a personal website for quite a while now. Somewhere to host personal and professional **ideas/experiences** that may deserve a dedicated **outlet** - aka brain dump. If any of the content presented herein is somehow useful, then I am coming one step closer to my major goal of paying back to the plethora of content contributors knitting such incredible open source communities I have been tapping knowledge from! *(It is hard to pinpoint one specific community e.g. R-Shiny folks, so take this term community in its broader sense)* My interests, combined with experiences in programming and data tools (see these on ["About"](http://renzocsilva.ca/about)), will be the pillars of this blog. For the [project section](http://renzocsilva.ca/project), I'd rather not make any promises at the moment... :smile:

Let's start with sharing (*and hopefully good karma!*): you can find the R-Blogdown code used to build this website [here](https://github.com/renzocsilva/webpage), and the original Hugo theme [here](https://github.com/naro143/hugo-coder-portfolio).

On a side note, here is a big shout-out to a few folks whose content and creativity indirectly inspired this initiative [Dean Atalli](https://deanattali.com/), [Yihui Xie](https://yihui.name) and [Bruno Hildenbrand](https://blog.hildenco.com/).

**Cheers!**

