---
title: 'A new old project'
author: Renzo C. Silva
date: '2019-09-16'
slug: a-new-old-project
categories: []
tags: []
description: ''
thumbnail: images/tn.png
---

**In 2018**, I engaged in a project, hired by a small environmental consultancy firm, to develop a web application (R Shiny). The idea was to simply automate part of their typical data processing workflow, for time-saving purposes, and develop a few data vizualization elements to assist in their reporting. As the subject area was not unfamiliar to me, I could confidently go one step further and help improving the workflow per se, including designing and implementing new metrics and processes. 

**A R-Shiny app was then deployed in a cloud server.** Happy client, great science, very exciting project... then life moves on.   

## Fast-forward 12 months

<p align = 'center'><iframe src="https://giphy.com/embed/t9lo3ViuLZaKTdM7xq" width="480" height="284" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></p>

**Here I am working on it again!** :smile: The new project goals are now focused (a) on the data preparation before its consumption by the current algorithm, and (b) making it fully customazible so that the experts, with some basic R skills, could tweak **any** parameters within it. 

**Reproducible science at its core!** Building such an RMarkdown document has been extremely **joyful**! 


## So what? 

The [USGS Database post series](https://renzocsilva.ca/posts/usgs-geochemdb-part1/) can wait. :wink:  
